FROM ghcr.io/bn-apps/base:latest

ENV DOTNET_ROOT=/root/.dotnet
ENV PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools" 

RUN apk add libgcc libicu libssl3 libstdc++ zlib ca-certificates-bundle
RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
    ./dotnet-install.sh --channel 8.0
