FROM ghcr.io/bn-apps/base:latest

ENV DOTNET_ROOT=/usr/local/bin/.dotnet
ENV PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools" 

RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | sh

RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
    ./dotnet-install.sh --install-dir $DOTNET_ROOT --channel 8.0
