FROM ghcr.io/bane-nor/base:latest

ARG DOTNET_VERSION
ENV DOTNET_VERSION=$DOTNET_VERSION

ENV DOTNET_ROOT=/usr/local/bin/.dotnet
ENV PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools" 
RUN  wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
    ./dotnet-install.sh --install-dir $DOTNET_ROOT --channel $DOTNET_VERSION --runtime aspnetcore 